language: elixir
elixir: 1.3.0
notifications:
  recipients:
    - roman.heinrich@gmail.comm
otp_release:
  - 19.0
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test"
before_install:
  # install inotifywait
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y inotify-tools
